#!/usr/bin/env python3
"""
build-index.py — derive the Knowledge-view graph data from the note pool.

Scans knowledge/notes/*.md, parses each note's YAML frontmatter (a small,
SCHEMA-SPECIFIC parser — no PyYAML dependency, so it runs anywhere), and emits
docs/assets/knowledge.js: the nodes + typed edges the interactive graph renders.

The index is DERIVED. Never hand-edit knowledge.js — edit the notes and re-run:
    python3 scripts/build-index.py
"""

import os
import re
import json
import datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NOTES_DIR = os.path.join(ROOT, "knowledge", "notes")
OUT = os.path.join(ROOT, "docs", "assets", "knowledge.js")
BLOB = "https://github.com/vikkybharadwaj/ai_knowledgecenter/blob/main/knowledge/notes/"

LAYERS = ["foundations", "api", "agent-sdk", "claude-code", "patterns", "products"]
LAYER_LABELS = {
    "foundations": "Foundations",
    "api": "Claude API",
    "agent-sdk": "Agent SDK",
    "claude-code": "Claude Code",
    "patterns": "Agent Patterns",
    "products": "Products & Consulting",
}


def split_frontmatter(text):
    """Return (frontmatter_str, body) or (None, text) if no frontmatter."""
    if not text.startswith("---"):
        return None, text
    end = text.find("\n---", 3)
    if end == -1:
        return None, text
    return text[3:end].strip("\n"), text[end + 4:]


def scalar(fm, key, default=None):
    m = re.search(r"^%s:\s*(.+?)\s*$" % re.escape(key), fm, re.MULTILINE)
    if not m:
        return default
    val = m.group(1).strip()
    if val.lower() in ("true", "false"):
        return val.lower() == "true"
    if (val.startswith('"') and val.endswith('"')) or (val.startswith("'") and val.endswith("'")):
        val = val[1:-1]
    return val


def parse_tags(fm):
    m = re.search(r"^tags:\s*\[(.*?)\]\s*$", fm, re.MULTILINE)
    if not m:
        return []
    return [t.strip().strip('"\'') for t in m.group(1).split(",") if t.strip()]


def parse_connections(fm):
    """Parse the `connections:` block of inline dicts:
         - { to: slug, type: kind, why: "..." }
       Uses targeted regex so commas/em-dashes inside `why` don't break parsing."""
    conns = []
    block = re.search(r"^connections:\s*\n(.*?)(?=^\S|\Z)", fm + "\n", re.MULTILINE | re.DOTALL)
    if not block:
        return conns
    for line in block.group(1).splitlines():
        line = line.strip()
        if not line.startswith("- "):
            continue
        to = re.search(r"\bto:\s*([A-Za-z0-9\-]+)", line)
        typ = re.search(r"\btype:\s*([A-Za-z\-]+)", line)
        why = re.search(r'\bwhy:\s*"(.*)"', line)
        if to and typ:
            conns.append({"to": to.group(1), "type": typ.group(1),
                          "why": why.group(1) if why else ""})
    return conns


def main():
    nodes, raw_edges = [], []
    for fn in sorted(os.listdir(NOTES_DIR)):
        if not fn.endswith(".md"):
            continue
        with open(os.path.join(NOTES_DIR, fn), encoding="utf-8") as f:
            fm, _ = split_frontmatter(f.read())
        if fm is None:
            print("  ! skipped (no frontmatter): %s" % fn)
            continue
        slug = scalar(fm, "slug") or fn[:-3]
        nodes.append({
            "slug": slug,
            "title": scalar(fm, "title", slug),
            "kind": scalar(fm, "kind", "concept"),
            "layer": scalar(fm, "spine_layer", "foundations"),
            "tags": parse_tags(fm),
            "depth": scalar(fm, "depth", "seedling"),
            "claudeSpecific": bool(scalar(fm, "claude_specific", True)),
            "url": BLOB + fn,
        })
        for c in parse_connections(fm):
            raw_edges.append({"from": slug, "to": c["to"], "type": c["type"], "why": c["why"]})

    known = {n["slug"] for n in nodes}
    edges, dropped = [], []
    for e in raw_edges:
        (edges if e["to"] in known else dropped).append(e)
    for e in dropped:
        print("  ! dropped edge to unknown note: %s -> %s" % (e["from"], e["to"]))

    # connection count (both directions) for node sizing
    deg = {n["slug"]: 0 for n in nodes}
    for e in edges:
        deg[e["from"]] += 1
        deg[e["to"]] += 1
    orphans = []
    for n in nodes:
        n["connCount"] = deg[n["slug"]]
        if n["kind"] == "concept" and deg[n["slug"]] == 0:
            orphans.append(n["slug"])

    data = {
        "generated": datetime.date.today().isoformat(),
        "layers": LAYERS,
        "layerLabels": LAYER_LABELS,
        "nodes": nodes,
        "edges": edges,
    }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("/* AUTO-GENERATED by scripts/build-index.py — do not edit by hand.\n")
        f.write("   Re-run after changing notes:  python3 scripts/build-index.py */\n")
        f.write("window.KC_DATA = " + json.dumps(data, indent=2, ensure_ascii=False) + ";\n")

    print("Wrote %s" % os.path.relpath(OUT, ROOT))
    print("  nodes: %d   edges: %d   dropped: %d" % (len(nodes), len(edges), len(dropped)))
    if orphans:
        print("  ⚠ ORPHAN concept notes (no connections — silo risk): %s" % ", ".join(orphans))
    else:
        print("  ✓ no orphans — every concept note is wired into the graph")


if __name__ == "__main__":
    main()
